# Generated by Django 5.2.4 on 2025-07-31 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='model_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subcategory'),
        ),
    ]
