# Generated by Django 5.2.4 on 2025-08-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video_model_name_alter_video_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='model_name',
        ),
    ]