# Generated by Django 5.2.4 on 2025-08-06 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_video_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category'),
        ),
        migrations.AddField(
            model_name='video',
            name='model_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.modelname'),
            preserve_default=False,
        ),
    ]
