# Generated by Django 5.2.4 on 2025-08-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_botuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='joined_at',
        ),
    ]
